version: "3.8"

services:
  web:
    container_name: php8
    volumes:
      - ../tugas-besar-1-wbd/src/public:/var/www/html
      - ../tugas-besar-1-wbd/src/app:/var/www/app
    build:
      context: ../tugas-besar-1-wbd
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=binotifyspotipai
      - MYSQL_DBNAME=binotifydb
    ports:
      - 8080:80
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=binotifyspotipai
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    restart: always

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    depends_on:
      - mysql
    ports:
      - 3535:8080

  binotify-premium-app:
    container_name: binotify-premium-app
    volumes:
      - ../binotify-premium-app/src:/react-vite-app/src
      - ../binotify-premium-app/public:/react-vite-app/public
    build:
      context: ../binotify-premium-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  binotify-rest:
    container_name: binotify-rest
    volumes:
      - ../binotify-rest:/express-app
    build:
      context: ../binotify-rest
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - DATABASE_URL=mysql://root:binotifyspotipai@mysql:3306/binotifyrest
    ports:
      - 5000:5000
    depends_on:
      - mysql
