version: "3.8"

services:
  web:
    container_name: php8
    volumes:
      - ../tugas-besar-1-wbd/src/public:/var/www/html
      - ../tugas-besar-1-wbd/src/app:/var/www/app
    build:
      context: ../tugas-besar-1-wbd
      dockerfile: Dockerfile
    environment:
      - MYSQL_DBHOST=mysql
      - MYSQL_DBPORT=3306
      - MYSQL_DBUSER=root
      - MYSQL_DBPASS=binotifyspotipai
      - MYSQL_DBNAME=binotifydb
      - SOAP_API_KEY=1fd89efa578ef3a8b81aef51cc868c0c4ec2b385cec0b7bc234e6ba7f53a02c4
      - SOAP_URL=http://hostlocal:4040
    ports:
      - 8080:80
    depends_on:
      - mysql
    extra_hosts:
      - "hostlocal:host-gateway"

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass InI_PasSW0rdNy4_Redis
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0.0
    container_name: mysql8
    environment:
      - MYSQL_ROOT_PASSWORD=binotifyspotipai
      - MYSQL_TCP_PORT=3306
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    restart: always

  adminer:
    container_name: adminer
    image: adminer:4.8.1
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    depends_on:
      - mysql
    ports:
      - 3535:8080

  binotify-premium-app:
    container_name: binotify-premium-app
    volumes:
      - ../binotify-premium-app/src:/react-vite-app/src
      - ../binotify-premium-app/public:/react-vite-app/public
    build:
      context: ../binotify-premium-app
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  binotify-rest:
    container_name: binotify-rest
    volumes:
      - ../binotify-rest:/express-app
    build:
      context: ../binotify-rest
      dockerfile: Dockerfile
    environment:
      - PORT=5000
      - DATABASE_URL=mysql://root:binotifyspotipai@mysql:3306/binotifyrest
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=InI_PasSW0rdNy4_Redis
      - SOAP_API_KEY=f9f768f063b9f0b831b9b7b51a0497656972425dc512f47e2f965d37de4e0915
      - SOAP_URL=http://hostlocal:4040
    ports:
      - 5000:5000
    depends_on:
      - mysql
    extra_hosts:
      - "hostlocal:host-gateway"

  # binotify-soap:
  #   container_name: binotify-soap
  #   build:
  #     context: ../binotify-soap
  #     dockerfile: Dockerfile
  #   environment:
  #     - DB_URL=jdbc:mysql://mysql8:3306/binotifysoap?useSSL=false
  #     - DB_Username=root
  #     - DB_Password=binotifyspotipai
  #     - HOST=localhost
  #     - PORT=4040
  #   ports:
  #     - 4040:4040
  #   depends_on:
  #     - mysql

volumes:
  redis_data:
    driver: local
